# Generated by Django 4.2.6 on 2024-01-01 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_category_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
