# Generated by Django 4.2.3 on 2024-03-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_personalinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
