# Generated by Django 4.1 on 2024-04-23 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_size_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
